version: '3.8'
services:
  backend:
    build: ./crawler-backend
    ports:
      - "5000:5000"
    restart: always
  frontend:
    build: ./crawler-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: always 